/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* Thu Jan 17 22:44:37 2019 */

/* parameterized module instance */
clk __ (.CLKI( ), .CLKOP( ));
